# -*- coding: utf-8 -*-
"""Triple Seasonal ARIMA_GHI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1UoN_2lxiLBe_ToI0_JzrQtbig6n29g

**Masukkan Data**
"""

from matplotlib import pyplot
import matplotlib as plt
import pandas as pd
import numpy as np

#Membaca Data
data = pd.read_csv('radiasi.txt', sep=';', header=0, low_memory=False, infer_datetime_format=True, parse_dates={'datetime':[0,1]}, index_col=['datetime'])
#Hasil 5 teratas
print(data.head())

#load data actual
data1 = pd.read_csv('radiasi.txt', sep=';', header=0, low_memory=False)
df = data1
df

"""**Visualisasi Plot Time Series**"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

ax = data.plot(color='dimgrey',figsize=(15,5),title='Plot Time Series Radiasi Matahari Global Kota Balikpapan');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import matplotlib as plt

ax = df['radiasi'].plot(color='dimgrey',figsize=(15,5),title='Plot Time Series Radiasi Matahari Global Kota Balikpapan');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

sample = df[:84]

import matplotlib as plt

ax = sample.plot(colormap='BrBG',figsize=(15,5),title='Plot Time Series Radiasi Matahari Global Kota Balikpapan Seminggu');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

"""**Visualisasi Plot Musiman Harian**"""

data1 = pd.read_csv('radiasi.txt', sep=';', header=0, low_memory=False)
df = data1

import pandas as pd
from datetime import datetime

df['date'] = pd.DatetimeIndex(df['date']).day_name()
dfa = pd.DataFrame(df, columns=['date', 'time', 'radiasi'])
dfa

dfb = dfa.groupby(['time','date'])['radiasi'].mean().unstack(fill_value=0).reset_index().rename_axis(None, axis=1)
dfb

import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (15,5)

plt.plot(dfb['Monday'],  '-+', label='Senin')
plt.plot(dfb['Tuesday'],  '-x', label='Selasa')
plt.plot(dfb['Wednesday'],  '-*', label='Rabu')
plt.plot(dfb['Thursday'],  '->', label='Kamis')
plt.plot(dfb['Friday'],  '-s', label='Jumat')
plt.plot(dfb['Saturday'],  '-o', label='Sabtu')
plt.plot(dfb['Sunday'],  '-p', label='Minggu')

plt.title('Plot Rata-Rata Harian')
plt.legend(fontsize=10,ncol=1)
plt.show()

"""**Visualisasi Plot Musiman Mingguan**"""

data1 = pd.read_csv('radiasi.txt', sep=';', header=0, low_memory=False)
df = data1

import pandas as pd
from datetime import datetime

df['date'] = pd.DatetimeIndex(df['date']).week
dfg = pd.DataFrame(df, columns=['date', 'time', 'radiasi'])
dfg

dfh = dfg.groupby(['time','date'])['radiasi'].mean().unstack(fill_value=0).reset_index().rename_axis(None, axis=1)
dfh

import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (15, 5)


plt.plot(dfh[1],  '-+', label='Minggu 1')
plt.plot(dfh[2],  '-x', label='Minggu 2')
plt.plot(dfh[3],  '-*', label='Minggu 3')
plt.plot(dfh[4],  '-v', label='Minggu 4')
plt.plot(dfh[5],  '-s', label='Minggu 5')
plt.plot(dfh[6],  '-o', label='Minggu 6')
plt.plot(dfh[7],  '-p', label='Minggu 7')
plt.plot(dfh[8],  '-1', label='Minggu 8')
plt.plot(dfh[9],  '-h', label='Minggu 9')
plt.plot(dfh[10],  '->', label='Minggu 10')
plt.plot(dfh[11],  '-^', label='Minggu 11')
plt.plot(dfh[12],  '-H', label='Minggu 12')
plt.plot(dfh[13],  '-+', label='Minggu 13')
plt.plot(dfh[14],  '-x', label='Minggu 14')
plt.plot(dfh[15],  '-*', label='Minggu 15')
plt.plot(dfh[16],  '-v', label='Minggu 16')
plt.plot(dfh[17],  '-s', label='Minggu 17')
plt.plot(dfh[18],  '-o', label='Minggu 18')
plt.plot(dfh[19],  '-p', label='Minggu 19')
plt.plot(dfh[20],  '-1', label='Minggu 20')
plt.plot(dfh[21],  '-h', label='Minggu 21')
plt.plot(dfh[22],  '->', label='Minggu 22')
plt.plot(dfh[23],  '-^', label='Minggu 23')
plt.plot(dfh[24],  '-H', label='Minggu 24')
plt.plot(dfh[25],  '-+', label='Minggu 25')
plt.plot(dfh[26],  '-x', label='Minggu 26')
plt.plot(dfh[26],  '-*', label='Minggu 27')
plt.plot(dfh[28],  '-v', label='Minggu 28')
plt.plot(dfh[29],  '-s', label='Minggu 29')
plt.plot(dfh[30],  '-o', label='Minggu 30')
plt.plot(dfh[31],  '-p', label='Minggu 31')
plt.plot(dfh[32],  '-1', label='Minggu 32')
plt.plot(dfh[33],  '-h', label='Minggu 33')
plt.plot(dfh[34],  '->', label='Minggu 34')
plt.plot(dfh[35],  '-^', label='Minggu 35')
plt.plot(dfh[36],  '-H', label='Minggu 36')
plt.plot(dfh[37],  '-+', label='Minggu 37')
plt.plot(dfh[38],  '-x', label='Minggu 38')
plt.plot(dfh[39],  '-*', label='Minggu 39')
plt.plot(dfh[40],  '-v', label='Minggu 40')
plt.plot(dfh[41],  '-s', label='Minggu 41')
plt.plot(dfh[42],  '-o', label='Minggu 42')
plt.plot(dfh[43],  '-p', label='Minggu 43')
plt.plot(dfh[44],  '-1', label='Minggu 44')
plt.plot(dfh[45],  '-h', label='Minggu 45')
plt.plot(dfh[46],  '->', label='Minggu 46')
plt.plot(dfh[47],  '-^', label='Minggu 47')
plt.plot(dfh[48],  '-H', label='Minggu 48')
plt.plot(dfh[49],  '-+', label='Minggu 49')
plt.plot(dfh[50],  '-x', label='Minggu 50')
plt.plot(dfh[51],  '-*', label='Minggu 51')
plt.plot(dfh[52],  '-v', label='Minggu 52')
plt.plot(dfh[53],  '-s', label='Minggu 53')

plt.title('Plot Rata-Rata Mingguan')
plt.legend(fontsize=10,ncol=6)
plt.show()

"""**Visualisasi Plot Musiman Bulanan**"""

data1 = pd.read_csv('radiasi.txt', sep=';', header=0, low_memory=False)
df = data1

import pandas as pd
from datetime import datetime

df['date'] = pd.DatetimeIndex(df['date']).month_name()
dfc = pd.DataFrame(df, columns=['date', 'time', 'radiasi'])
dfc

dfd = dfc.groupby(['time','date'])['radiasi'].mean().unstack(fill_value=0).reset_index().rename_axis(None, axis=1)
dfd

import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (15, 5)


plt.plot(dfd['January'],  '-+', label='Januari')
plt.plot(dfd['February'],  '-x', label='Februari')
plt.plot(dfd['March'],  '-*', label='Maret')
plt.plot(dfd['April'],  '-v', label='April')
plt.plot(dfd['May'],  '-s', label='Mei')
plt.plot(dfd['June'],  '-o', label='Juni')
plt.plot(dfd['July'],  '-p', label='Juli')
plt.plot(dfd['August'],  '-1', label='Agustus')
plt.plot(dfd['September'],  '-h', label='September')
plt.plot(dfd['October'],  '->', label='Oktober')
plt.plot(dfd['November'],  '-^', label='November')
plt.plot(dfd['December'],  '-H', label='Desember')

plt.title('Plot Rata-Rata Bulanan')
plt.legend(fontsize=10,ncol=3)
plt.show()

"""**Visualisasi Plot Musiman Tahunan**"""

data1 = pd.read_csv('radiasi.txt', sep=';', header=0, low_memory=False)
df = data1

import pandas as pd
from datetime import datetime

df['date'] = pd.DatetimeIndex(df['date']).year
dfe = pd.DataFrame(df, columns=['date', 'time', 'radiasi'])
dfe

dff = dfe.groupby(['time','date'])['radiasi'].mean().unstack(fill_value=0).reset_index().rename_axis(None, axis=1)
dff

import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (15, 5)


plt.plot(dff[2010],  '-+', label='2010')
plt.plot(dff[2011],  '-x', label='2011')
plt.plot(dff[2012],  '-*', label='2012')
plt.plot(dff[2013],  '-v', label='2013')
plt.plot(dff[2014],  '-s', label='2014')
plt.plot(dff[2015],  '-o', label='2015')
plt.plot(dff[2016],  '-p', label='2016')
plt.plot(dff[2017],  '-1', label='2017')
plt.plot(dff[2018],  '-h', label='2018')

plt.title('Plot Rata-Rata Tahunan')
plt.legend(fontsize=10,ncol=3)
plt.show()

"""**Mingguan**"""

minggu = df[:84].reset_index()
minggu1 = df[84:168].reset_index()
minggu2 = df[168:252].reset_index()
minggu3 = df[252:336].reset_index()
minggu4 = df[336:420].reset_index()
minggu5 = df[420:504].reset_index()
minggu6 = df[504:588].reset_index()
minggu7 = df[588:672].reset_index()
minggu8 = df[672:756].reset_index()

import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (15, 5)


plt.plot(minggu['radiasi'],  '-+', label='Minggu 1')
plt.plot(minggu1['radiasi'],  '-x', label='Minggu 2')
plt.plot(minggu2['radiasi'],  '-*', label='Minggu 3')
plt.plot(minggu3['radiasi'],  '-v', label='Minggu 4')
plt.plot(minggu4['radiasi'],  '-s', label='Minggu 5')
plt.plot(minggu5['radiasi'],  '-o', label='Minggu 6')
plt.plot(minggu6['radiasi'],  '-p', label='Minggu 7')
plt.plot(minggu7['radiasi'],  '-1', label='Minggu 8')
plt.plot(minggu8['radiasi'],  '-h', label='Minggu 9')

plt.title('Plot Musiman Mingguan')
plt.legend(fontsize=10,ncol=3)
plt.show()

"""**Tahunan**"""

tahun1 = df[:4368]
tahun1

tahun1 = df[:4368].reset_index()
tahun2 = df[4368:8736].reset_index()
tahun3 = df[8736:13104].reset_index()
tahun4 = df[13104:17472].reset_index()
tahun5 = df[17472:21840].reset_index()
tahun6 = df[21840:26208].reset_index()
tahun7 = df[26208:30576].reset_index()
tahun8 = df[30576:34944].reset_index()
tahun9 = df[34944:39312].reset_index()

import matplotlib as plt

ax = tahun1['radiasi'].plot(color='dimgrey',figsize=(10,5),title='Plot Radiasi Matahari Global Tahun 2010');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import matplotlib as plt

ax = tahun2['radiasi'].plot(color='dimgrey',figsize=(10,5),title='Plot Radiasi Matahari Global Tahun 2011');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import matplotlib as plt

ax = tahun3['radiasi'].plot(color='dimgrey',figsize=(10,5),title='Plot Radiasi Matahari Global Tahun 2012');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import matplotlib as plt

ax = tahun4['radiasi'].plot(color='dimgrey',figsize=(10,5),title='Plot Radiasi Matahari Global Tahun 2013');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import matplotlib as plt

ax = tahun5['radiasi'].plot(color='dimgrey',figsize=(10,5),title='Plot Radiasi Matahari Global Tahun 2014');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import matplotlib as plt

ax = tahun6['radiasi'].plot(color='dimgrey',figsize=(10,5),title='Plot Radiasi Matahari Global Tahun 2015');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import matplotlib as plt

ax = tahun7['radiasi'].plot(color='dimgrey',figsize=(10,5),title='Plot Radiasi Matahari Global Tahun 2016');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import matplotlib as plt

ax = tahun8['radiasi'].plot(color='dimgrey',figsize=(10,5),title='Plot Radiasi Matahari Global Tahun 2017');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import matplotlib as plt

ax = tahun9['radiasi'].plot(color='dimgrey',figsize=(10,5),title='Plot Radiasi Matahari Global Tahun 2018');
ax.set_xlabel("Waktu")
ax.set_ylabel("Radiasi")

import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (15, 5)


plt.plot(tahun1['radiasi'], label='1')
plt.plot(tahun2['radiasi'], label='2')
plt.plot(tahun3['radiasi'], label='3')
plt.plot(tahun4['radiasi'], label='4')
plt.plot(tahun5['radiasi'], label='5')
plt.plot(tahun6['radiasi'], label='6')
plt.plot(tahun7['radiasi'], label='7')
plt.plot(tahun8['radiasi'], label='8')
plt.plot(tahun9['radiasi'], label='9')

plt.title('Plot Musiman Mingguan')
plt.legend(fontsize=10,ncol=3)
plt.show()

fig, (ax1, ax2, ax3, ax4, ax5, ax6, ax7, ax8, ax9) = plt.subplots(9, 1, figsize=(30,36))
axa = tahun1['radiasi'].plot(colormap='Dark2',figsize=(12,8),title='1', ax=ax1);
axa.set_xlabel("Waktu")
axa.set_ylabel("Jumlah)")
axx = tahun2['radiasi'].plot(colormap='BrBG',figsize=(12,8),title='2', ax=ax2);
axx.set_xlabel("Waktu")
axx.set_ylabel("Jumlah)")
axy = tahun3['radiasi'].plot(colormap='BrBG_r',figsize=(12,8),title='3', ax=ax3);
axy.set_xlabel("Waktu")
axy.set_ylabel("Jumlah)")
axz = tahun4['radiasi'].plot(colormap='Dark2',figsize=(12,8),title='4', ax=ax4);
axz.set_xlabel("Waktu")
axz.set_ylabel("Jumlah)")
axb = tahun5['radiasi'].plot(colormap='BrBG',figsize=(12,8),title='5', ax=ax5);
axb.set_xlabel("Waktu")
axb.set_ylabel("Jumlah)")
axc = tahun6['radiasi'].plot(colormap='BrBG_r',figsize=(12,8),title='6', ax=ax6);
axc.set_xlabel("Waktu")
axc.set_ylabel("Jumlah)")
axd = tahun7['radiasi'].plot(colormap='Dark2',figsize=(12,8),title='7', ax=ax7);
axd.set_xlabel("Waktu")
axd.set_ylabel("Jumlah)")
axe = tahun8['radiasi'].plot(colormap='BrBG',figsize=(12,8),title='8', ax=ax8);
axe.set_xlabel("Waktu")
axe.set_ylabel("Jumlah)")
axf = tahun9['radiasi'].plot(colormap='BrBG_r',figsize=(12,8),title='9', ax=ax9);
axf.set_xlabel("Waktu")
axf.set_ylabel("Jumlah)")

"""**Box Cox Transformation**"""

#load data actual
datain = pd.read_csv('insample.txt', sep=';', header=0, low_memory=False)
di = datain
di

from scipy.stats import boxcox

di['radiasi'], lam = boxcox(di['radiasi'])
print('Lambda: %f' % lam)
pyplot.figure(1)
# line plot
pyplot.subplot(211)
pyplot.plot(di['radiasi'])
# histogram
pyplot.subplot(212)
pyplot.hist(di['radiasi'])
pyplot.show()

#load data actual
data2 = pd.read_csv('transformasi.txt', sep=';', header=0, low_memory=False)
dt = data2
dt

from scipy.stats import boxcox

dt['radiasi'], lam = boxcox(dt['radiasi'])
print('Lambda: %f' % lam)
pyplot.figure(1)
# line plot
pyplot.subplot(211)
pyplot.plot(dt['radiasi'])
# histogram
pyplot.subplot(212)
pyplot.hist(dt['radiasi'])
pyplot.show()

"""**Visualisasi Plot ACF dan PACF**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['figure.figsize'] = (35, 5)
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Create figure
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(24,12))

# Plot the ACF of data
acf=plot_acf(df['radiasi'], lags=240, zero=False, ax=ax1, color='green');


# Plot the PACF of data
pacf=plot_pacf(df['radiasi'], lags=100, zero=False, ax=ax2, color='blue');

#load data actual
data2 = pd.read_csv('transformasi.txt', sep=';', header=0, low_memory=False)
dt = data2
dt

#load data actual
data3 = pd.read_csv('differencing.txt', sep=';', header=0, low_memory=False)
ds = data3
ds